import { browser, by, element } from 'protractor';

/**
 * auto generate class. No modified needed.
 */
export class AppPage {
  /** autogenerated. no modified needed */
  navigateTo() {
    return browser.get(browser.baseUrl) as Promise<any>;
  }

  /** autogenerated. no modified needed */
  getTitleText() {
    return element(by.css('app-root .content span')).getText() as Promise<string>;
  }
}
